### ISSUE TITLE
 [MacOS-Arc-397-login] 회원가입, 로그인에서 이메일 유효성에 따른 Submit 버튼 통제가 다른것 같습니다.

### ISSUE THREAD

**Issue by Unagi-zoso** [100-hours-a-week/2-eddie-lee-community-fe#1]
**버그 설명**
`q@q.q` 란 이메일로 회원가입을 시도했습니다. 헬퍼 텍스트로 유효성 관련 에러 메시지를 받았지만
막상 회원가입 Submit 버튼을 누르니 성공했습니다.
이후 로그인을 하려하니 이메일 유효성에 의해 Submit 버튼이 disable 된듯한 반응이 나타났습니다.
회원가입, 로그인에서 통일감있는 반응을 준다면 좋을 것 같습니다.

요약하자면 회원가입 시 유효성에 어긋나면 실패하는게 좋을 것 같습니다!

**재현하는 방법**
동작을 재현하는 단계:
1. 회원가입 페이지로 갑니다.
2. 이메일에 `q@q.q` 를 기입합니다. (다른 input 들은 유효한 값들로 작성)
3. 회원가입 버튼 클릭 (로그인으로 리다이렉트)
4. 회원가입 내용으로 로그인 시도 (로그인 실패)

**예상한 동작**
유효하지 않은 이메일로 회원가입이 실패하길 기대했습니다.

**스크린샷**

![스크린샷 2024-12-17 오후 4 03 55](https://github.com/user-attachments/assets/ef1c8678-158c-4778-a4cd-d65578571bbb)
![스크린샷 2024-12-17 오후 4 04 14](https://github.com/user-attachments/assets/19b0d949-5c3a-478c-a835-64aa43f471bd)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS:MacOS 14.3(23D56)
 - Browser Arc

**추가적인 내용:**
냐옹

**Comment by kjr2020** [comment]
안녕하세요 스완, 해당 이슈가 해결됐습니당~!

먼저, 조건문에서 형식에 안맞고, 중복이 아닌 친구를 못걸렀던 문제가 있었습니다.
조건문 수정해서 해결했습니다.
두 번째로 DB에서 컬럼을 생성할 때, email이랑 nickname에 unique 옵션이 없음을 확인했습니다.
이 부분도 해결했습니다.

스완이 겪었던 문제는 그저 로그인으로 리다이렉트가 되는게 아니라 이메일 형식을 맞추지 않은 유저가 생성되고 있었어요~
근데, 로그인 버튼은 이메일에 대한 조건문이 잘 걸려있어서 버튼이 활성화가 안됐기 때문에 로그인이 안됐었습니다~!

이슈 제보 감사드리고 심심할 때 또 놀러와서 이슈잡아주십쇼~!

내일 딥다이브인데 화이팅하시기 바랍니다!
