### ISSUE TITLE
회원수정,비밀번호 변경 페이지 UX 

### ISSUE THREAD

**Issue by yosep98** [100-hours-a-week/2-eddie-lee-community-fe#2]
회원 수정, 비밀번호 변경창에서 게시글 창으로 이동하는 애로우 버튼이나 다른 방법이 있으면 좋을 것 같습니당.

**Comment by kjr2020** [comment]
안녕하세요 셉,

먼저, 이슈 제보에 대해 감사드립니다~!
셉이 말씀해주신 이슈는 뒤로가기버튼 추가로 해결되었습니다~!

다음에도 들러서 이슈 등록해주시면 감사하겠습니다!

내일 딥다이브인데 화이팅하시길 바랍니다~!
