### ISSUE TITLE
로그인, 회원가입 버튼같은 클릭 요소들은 클릭 가능한 요소라는 걸 알려줬으면 좋겠습니다

### ISSUE THREAD

**Issue by SeHyeonLee-dev** [100-hours-a-week/2-eddie-lee-community-fe#3]
별거 아니긴 하지만 사소하게 신경쓰이는 부분인 것 같습니다

**Comment by kjr2020** [comment]
의견 감사합니다~!
제가 잘 이해를 못해서 그런데 클릭이 가능한 요소라는걸 알려준다는게 어떤 의미일까용?

**Comment by SeHyeonLee-dev** [comment]
예를 들면 css에 cursor: pointer 같은 걸 줘서 마우스 포인터를 바꿔서 아 이건 클릭 가능한 요소구나 라고 사용자한테 알려줄 수 있으면 좋겠다는 의미였습니다!

**Comment by kjr2020** [comment]
> 예를 들면 css에 cursor: pointer 같은 걸 줘서 마우스 포인터를 바꿔서 아 이건 클릭 가능한 요소구나 라고 사용자한테 알려줄 수 있으면 좋겠다는 의미였습니다!

아아 감사합니다~! 적용해보겠습니다!
