### ISSUE TITLE
 [windows-firefox-1080p] 회원정보 수정 페이지 관련

### ISSUE THREAD

**Issue by notedsj** [100-hours-a-week/2-eddie-lee-community-fe#5]
**버그 설명**
1. 회원 삭제가 안됨.
![image](https://github.com/user-attachments/assets/bf9eb9b8-4fd8-4ba5-a9d7-81ad14ac01a7)
아래 이미지에서 취소를 누르면 모달창이 잘 닫히지만 삭제를 누를시 아무 반응이 없고 위 사진과 같은 에러가 발생.
![image](https://github.com/user-attachments/assets/2427e6d0-e025-45a2-acd4-5f6126c5783f)

2. 모달창과 토스트 메세지 css 오류?
위의 모달창 이미지와 아래 토스트 이미지 참고.
![image](https://github.com/user-attachments/assets/e90f9e7b-0a2e-46e6-8252-87917e4d4d28)

3. 회원가입시에 프로필 이미지를 등록했어도 회원정보수정에서 수정을 거치면 원래 업로드 했던 프로필이 날아감.

3번의 동작을 재현하는 단계:
- 회원가입시 이미지 등록
- 회원수정 페이지 접속
- 닉네임만 변경 후 회원수정 클릭
- 토스트 메세지 오류 확인때문에 수정버튼 여러번 누름. (이거때문에 날라가는지. 그냥 이미지 업로드 안하고 수정 누르면 날아가는지 확인 필요.)

**데스크톱(다음 정보를 작성해 주세요):**
 - OS: windows
 - Browser: firefox recent
 
**추가적인 내용:**
게시판에서 제일 최신 게시글이 상단으로 오도록 내림차순 정렬이 되어있었으면 좋을 것 같아요!

**Comment by kjr2020** [comment]
어..음...이유가 뭘까요..... 방금 확인했는데 저는 잘됐거든요... 윈도우/맥차이는 아닐거같은데 윈도우로도 한 번 확인해보겠습니다!

**Comment by notedsj** [comment]
1번 issue - 잠깐 서버가 이상할때 했나봐요. 방금 해보니 탈퇴가 잘 되네요.
2번 issue - css오류 똑같이나요..
3번 issue - 회원수정페이지에서 f5(강제 새로고침)을 하니까 이미지가 날라가는것을 확인했습니다만 다른 페이지 갔다가 다시 로드하니 정삭적으로 불러와지네요.

**Comment by kjr2020** [comment]
> 1번 issue - 잠깐 서버가 이상할때 했나봐요. 방금 해보니 탈퇴가 잘 되네요. 2번 issue - css오류 똑같이나요.. 3번 issue - 회원수정페이지에서 f5(강제 새로고침)을 하니까 이미지가 날라가는것을 확인했습니다만 다른 페이지 갔다가 다시 로드하니 정삭적으로 불러와지네요.

아 넵 아직 수정한건아니구 로그아웃만 해봤는데 작동해서 ㅎㅎ 수정 되면 댓글 한 번 더 달아드리겠습니다!

**Comment by kjr2020** [comment]
수정완료했습니다~!
